kind: Service
apiVersion: v1
metadata:
  name: svc-pytorch-v2
  labels:
    name: svc-pytorch-v2
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      name: jupyter
  selector:
    name: pytorch-v2